### ISSUE TITLE
error of too many arguments

### ISSUE THREAD

**Issue by bonviesinfo** [demo-apps/go-gin-app#26]
hi 
when I run the code  it shows 
"./handlers.user.go:31:14: too many arguments in call to c.SetCookie
	have (string, string, number, string, string, http.SameSite, bool, bool)
	want (string, string, int, string, string, bool, bool)
./handlers.user.go:58:13: too many arguments in call to c.SetCookie
	have (string, string, number, string, string, http.SameSite, bool, bool)
	want (string, string, int, string, string, bool, bool)
./handlers.user.go:80:14: too many arguments in call to c.SetCookie
	have (string, string, number, string, string, http.SameSite, bool, bool)
	want (string, string, int, string, string, bool, bool)"

could you help sove it ?

**Comment by dasider41** [comment]
Remove `http.SameSite` from arguments. the code works well without the option.

**Comment by Azzstyle** [comment]
same site only worked in go 1.11 ，remove this option word well as well

**Comment by senanito85** [comment]
> Remove `http.SameSite` from arguments. the code works well without the option.

Thank you! this helped to fix the issue.
